config/routes.rb
Rails.application.routes.draw do

  get '/artists/random', to: 'artists#random'
  post '/artists/random', to: 'artists#random'


  resources :artist_similarities
  resources :similar_artists
  resources :artists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "main#home"
end

app/models/artist_similarity.rb
class ArtistSimilarity < ApplicationRecord
  belongs_to :artist
  belongs_to :similar_artist
end

app/controllers/artist_similarities_controller.rb
class ArtistSimilaritiesController < ApplicationController
  before_action :set_artist_similarity, only: [:show, :edit, :update, :destroy]

  # GET /artist_similarities
  # GET /artist_similarities.json
  def index
    @artist_similarities = ArtistSimilarity.all
  end

  # GET /artist_similarities/1
  # GET /artist_similarities/1.json
  def show
  end

  # GET /artist_similarities/new
  def new
    @artist_similarity = ArtistSimilarity.new
  end

  # GET /artist_similarities/1/edit
  def edit
  end

  # POST /artist_similarities
  # POST /artist_similarities.json
  def create
    @artist_similarity = ArtistSimilarity.new(artist_similarity_params)

    respond_to do |format|
      if @artist_similarity.save
        format.html { redirect_to @artist_similarity, notice: 'Artist similarity was successfully created.' }
        format.json { render :show, status: :created, location: @artist_similarity }
      else
        format.html { render :new }
        format.json { render json: @artist_similarity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artist_similarities/1
  # PATCH/PUT /artist_similarities/1.json
  def update
    respond_to do |format|
      if @artist_similarity.update(artist_similarity_params)
        format.html { redirect_to @artist_similarity, notice: 'Artist similarity was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist_similarity }
      else
        format.html { render :edit }
        format.json { render json: @artist_similarity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artist_similarities/1
  # DELETE /artist_similarities/1.json
  def destroy
    @artist_similarity.destroy
    respond_to do |format|
      format.html { redirect_to artist_similarities_url, notice: 'Artist similarity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist_similarity
      @artist_similarity = ArtistSimilarity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_similarity_params
      params.require(:artist_similarity).permit(:artist_id, :similar_artist_id)
    end
end

app/helpers/artist_similarities_helper.rb
module ArtistSimilaritiesHelper
end

app/views/artist_similarities/_form.html.erb
<%= form_for(artist_similarity) do |f| %>
  <% if artist_similarity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist_similarity.errors.count, "error") %> prohibited this artist_similarity from being saved:</h2>

      <ul>
      <% artist_similarity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artist_id %>
    <%= f.text_field :artist_id %>
  </div>

  <div class="field">
    <%= f.label :similar_artist_id %>
    <%= f.text_field :similar_artist_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artist_similarities/edit.html.erb
<h1>Editing Artist Similarity</h1>

<%= render 'form', artist_similarity: @artist_similarity %>

<%= link_to 'Show', @artist_similarity %> |
<%= link_to 'Back', artist_similarities_path %>

app/views/artist_similarities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artist Similarities</h1>

<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Similar artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artist_similarities.each do |artist_similarity| %>
      <tr>
        <td><%= artist_similarity.artist.name %></td>
        <td><%= artist_similarity.similar_artist.name %></td>
        <td><%= link_to 'Show', artist_similarity %></td>
        <td><%= link_to 'Edit', edit_artist_similarity_path(artist_similarity) %></td>
        <td><%= link_to 'Destroy', artist_similarity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist Similarity', new_artist_similarity_path %>
<%= link_to 'Back', root_path %>

app/views/artist_similarities/new.html.erb
<h1>New Artist Similarity</h1>

<%= render 'form', artist_similarity: @artist_similarity %>

<%= link_to 'Back', artist_similarities_path %>

app/views/artist_similarities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= @artist_similarity.artist %>
</p>

<p>
  <strong>Similar artist:</strong>
  <%= @artist_similarity.similar_artist %>
</p>

<%= link_to 'Edit', edit_artist_similarity_path(@artist_similarity) %> |
<%= link_to 'Back', artist_similarities_path %>