config/routes.rb
Rails.application.routes.draw do

  get '/artists/random', to: 'artists#random'
  post '/artists/random', to: 'artists#random'


  resources :artist_similarities
  resources :similar_artists
  resources :artists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "main#home"
end

app/models/artist.rb
class Artist < ApplicationRecord

  has_many :artist_similarities
  has_many :similar_artists, through: :artist_similarities




  def similar_artists_lastfm

    @similar_artists_lastfm = []

    require 'net/http'
    require 'json'

    uri = URI('http://ws.audioscrobbler.com/2.0/')
    params = {
      :method => 'artist.getsimilar',
      :artist => self.name,
      :api_key => '649104dbc970cbc72a343fa37daaab71',
      :format => 'json'
    }
    uri.query = URI.encode_www_form(params)
    res = Net::HTTP.get_response(uri)
    content = JSON.parse(res.body) if res.is_a?(Net::HTTPSuccess)
    @similar_artists_lastfm = content["similarartists"]["artist"]

  end





end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show

    # http://ws.audioscrobbler.com/2.0/?method=artist.getsimilar&artist=cher&api_key=98eb1de341bb8867330d52e277726f6a&format=json

    require 'net/http'
    require 'json'

    uri = URI('http://ws.audioscrobbler.com/2.0/')
    params = {
      :method => 'artist.getsimilar',
      :artist => @artist.name,
      :api_key => '649104dbc970cbc72a343fa37daaab71',
      :format => 'json'
    }
    uri.query = URI.encode_www_form(params)

    res = Net::HTTP.get_response(uri)
    # puts res.body if res.is_a?(Net::HTTPSuccess)
    content = JSON.parse(res.body) if res.is_a?(Net::HTTPSuccess)

    logger.debug "content"
    logger.debug content


    # logger.debug "content.similarartists"
    # logger.debug content.similarartists

    @content = content

    # @artist.similar_artists_lastfm = content.similarartists.artist
    @similar_artists_lastfm = content["similarartists"]["artist"]


  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end



  # POST /random
  # POST /random.json
  def random
    limit = limit_params[:limit]
    @artists = Artist.order("RANDOM()").limit(limit)
  end





  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :description, :genre, :image, :birthDate, :deathDate, :activeFrom, :activeUntil)
    end

    def limit_params
      params.permit(:limit)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for(artist) do |f| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :birthDate %>
    <%= f.datetime_select :birthDate %>
  </div>

  <div class="field">
    <%= f.label :deathDate %>
    <%= f.datetime_select :deathDate %>
  </div>

  <div class="field">
    <%= f.label :activeFrom %>
    <%= f.datetime_select :activeFrom %>
  </div>

  <div class="field">
    <%= f.label :activeUntil %>
    <%= f.datetime_select :activeUntil %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Genre</th>
      <th>Image</th>
      <th>Birth date</th>
      <th>Death date</th>
      <th>Active from</th>
      <th>Active until</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.description %></td>
        <td><%= artist.genre %></td>
        <td><img src="<%= artist.image %>" alt=""></td>
        <td><%= artist.birthDate.year %></td>
        <td><%= artist.deathDate.year %></td>
        <td><%= artist.activeFrom.year %></td>
        <td><%= artist.activeUntil.year %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>
<%= link_to 'Back', root_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/random.html.erb
<p id="notice"><%= notice %></p>

<h1>Ramdom Artists</h1>

<div style="margin-bottom: 20px;">
<%= form_tag("", method: "get") do %>
  <%= label_tag(:limit, "Limit: ") %>
  <%= text_field_tag(:limit, 1) %>
  <%= submit_tag("OK") %>
<% end %>
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Genre</th>
      <th>Image</th>
      <th>Birth date</th>
      <th>Death date</th>
      <th>Active from</th>
      <th>Active until</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.description %></td>
        <td><%= artist.genre %></td>
        <td><img src="<%= artist.image %>" alt=""></td>
        <td><%= artist.birthDate.year %></td>
        <td><%= artist.deathDate.year %></td>
        <td><%= artist.activeFrom.year %></td>
        <td><%= artist.activeUntil.year %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>
<%= link_to 'Back', root_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<img src="<%= @artist.image %>" alt="<%= @artist.name %>">

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @artist.description %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @artist.genre %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @artist.birthDate.year %>
</p>

<p>
  <strong>Death date:</strong>
  <%= @artist.deathDate.year %>
</p>

<p>
  <strong>Active from:</strong>
  <%= @artist.activeFrom.year %>
</p>

<p>
  <strong>Active until:</strong>
  <%= @artist.activeUntil.year %>
</p>



<h1>Similar Artists - In database</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Genre</th>
      <th>Image</th>
      <th>Birthdate</th>
      <th>Deathdate</th>
      <th>Activefrom</th>
      <th>Activeuntil</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artist.similar_artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.description %></td>
        <td><%= artist.genre %></td>
        <td><img src="<%= artist.image %>" alt=""></td>
        <!-- <td><%= artist.birthDate %></td>
        <td><%= artist.deathDate %></td>
        <td><%= artist.activeFrom %></td>
        <td><%= artist.activeUntil %></td> -->
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>






<h1>Similar Artists - Last.fm</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
    </tr>
  </thead>

  <tbody>
    <% @similar_artists_lastfm.each do |artist| %>
      <tr>
        <td><%= artist["name"] %></td>
        <td><img src="<%= artist['image'][0]['#text'] %>" alt=""></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>