config/routes.rb
Rails.application.routes.draw do

  get '/artists/random', to: 'artists#random'
  post '/artists/random', to: 'artists#random'


  resources :artist_similarities
  resources :similar_artists
  resources :artists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "main#home"
end

app/models/similar_artist.rb
class SimilarArtist < ApplicationRecord

  has_many :artist_similarities
  has_many :artists, through: :artist_similarities

end

app/controllers/similar_artists_controller.rb
class SimilarArtistsController < ApplicationController
  before_action :set_similar_artist, only: [:show, :edit, :update, :destroy]

  # GET /similar_artists
  # GET /similar_artists.json
  def index
    @similar_artists = SimilarArtist.all
  end

  # GET /similar_artists/1
  # GET /similar_artists/1.json
  def show
  end

  # GET /similar_artists/new
  def new
    @similar_artist = SimilarArtist.new
  end

  # GET /similar_artists/1/edit
  def edit
  end

  # POST /similar_artists
  # POST /similar_artists.json
  def create
    @similar_artist = SimilarArtist.new(similar_artist_params)

    respond_to do |format|
      if @similar_artist.save
        format.html { redirect_to @similar_artist, notice: 'Similar artist was successfully created.' }
        format.json { render :show, status: :created, location: @similar_artist }
      else
        format.html { render :new }
        format.json { render json: @similar_artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /similar_artists/1
  # PATCH/PUT /similar_artists/1.json
  def update
    respond_to do |format|
      if @similar_artist.update(similar_artist_params)
        format.html { redirect_to @similar_artist, notice: 'Similar artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @similar_artist }
      else
        format.html { render :edit }
        format.json { render json: @similar_artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /similar_artists/1
  # DELETE /similar_artists/1.json
  def destroy
    @similar_artist.destroy
    respond_to do |format|
      format.html { redirect_to similar_artists_url, notice: 'Similar artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_similar_artist
      @similar_artist = SimilarArtist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def similar_artist_params
      params.require(:similar_artist).permit(:name, :description, :genre, :image, :birthDate, :deathDate, :activeFrom, :activeUntil, :artist_id)
    end
end

app/helpers/similar_artists_helper.rb
module SimilarArtistsHelper
end

app/views/similar_artists/_form.html.erb
<%= form_for(similar_artist) do |f| %>
  <% if similar_artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(similar_artist.errors.count, "error") %> prohibited this similar_artist from being saved:</h2>

      <ul>
      <% similar_artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :birthDate %>
    <%= f.datetime_select :birthDate %>
  </div>

  <div class="field">
    <%= f.label :deathDate %>
    <%= f.datetime_select :deathDate %>
  </div>

  <div class="field">
    <%= f.label :activeFrom %>
    <%= f.datetime_select :activeFrom %>
  </div>

  <div class="field">
    <%= f.label :activeUntil %>
    <%= f.datetime_select :activeUntil %>
  </div>

  <div class="field">
    <%= f.label :artist_id %>
    <%= f.number_field :artist_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/similar_artists/edit.html.erb
<h1>Editing Similar Artist</h1>

<%= render 'form', similar_artist: @similar_artist %>

<%= link_to 'Show', @similar_artist %> |
<%= link_to 'Back', similar_artists_path %>

app/views/similar_artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Similar Artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Genre</th>
      <th>Image</th>
      <th>Birth date</th>
      <th>Death date</th>
      <th>Active from</th>
      <th>Active until</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @similar_artists.each do |similar_artist| %>
      <tr>
        <td><%= similar_artist.name %></td>
        <td><%= similar_artist.description %></td>
        <td><%= similar_artist.genre %></td>
        <td><img src="<%= similar_artist.image %>" alt=""></td>
        <td><%= similar_artist.birthDate %></td>
        <td><%= similar_artist.deathDate %></td>
        <td><%= similar_artist.activeFrom %></td>
        <td><%= similar_artist.activeUntil %></td>
        <td><%= similar_artist.artist_id %></td>
        <td><%= link_to 'Show', similar_artist %></td>
        <td><%= link_to 'Edit', edit_similar_artist_path(similar_artist) %></td>
        <td><%= link_to 'Destroy', similar_artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Similar Artist', new_similar_artist_path %>
<%= link_to 'Back', root_path %>

app/views/similar_artists/new.html.erb
<h1>New Similar Artist</h1>

<%= render 'form', similar_artist: @similar_artist %>

<%= link_to 'Back', similar_artists_path %>

app/views/similar_artists/show.html.erb
<p id="notice"><%= notice %></p>

<img src="<%= @similar_artist.image %>" alt="<%= @similar_artist.name %>">


<p>
  <strong>Name:</strong>
  <%= @similar_artist.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @similar_artist.description %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @similar_artist.genre %>
</p>

<p>
  <strong>Image:</strong>
  <%= @similar_artist.image %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @similar_artist.birthDate %>
</p>

<p>
  <strong>Deathdate:</strong>
  <%= @similar_artist.deathDate %>
</p>

<p>
  <strong>Activefrom:</strong>
  <%= @similar_artist.activeFrom %>
</p>

<p>
  <strong>Activeuntil:</strong>
  <%= @similar_artist.activeUntil %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @similar_artist.artist_id %>
</p>

<%= link_to 'Edit', edit_similar_artist_path(@similar_artist) %> |
<%= link_to 'Back', similar_artists_path %>